USE SearchData;
INSERT INTO Clinic VALUES (3,'NAGAR', 'BANGALORE', 'BUILDAFINA VISTA', 'BEHIND IIM BANGALORE');
INSERT INTO Doctor VALUES (3,'ANANy',1,'MBBS, Phd',5,'cardiologist',9542592402,2,'ANNA@BANNA.COM');
SELECT * FROM Doctor;
